
export let nutcodes = ["208","204","606","203","205","269","291","601","301","312","303","304","315","305","306","307","317","309","421","320","404","405","406","410","415","417","418","401","328","323","430","619","618"];

export let nutInfo = {
"203":{"unit":"g","long_name":"Protein", "short_name":"Prot"},
"204":{"unit":"g","long_name":"Total lipid (fat)", "short_name":"Fat"},
"205":{"unit":"g","long_name":"Carbohydrate, by difference", "short_name":"Carb"},
"208":{"unit":"kcal","long_name":"Energy", "short_name":"Cals"},
"269":{"unit":"g","long_name":"Sugars, total", "short_name":"Sug"},
"291":{"unit":"g","long_name":"Fiber, total dietary", "short_name":"Fib"},
"301":{"unit":"mg","long_name":"Calcium, Ca", "short_name":"Ca"},
"303":{"unit":"mg","long_name":"Iron, Fe", "short_name":"Fe"},
"304":{"unit":"mg","long_name":"Magnesium, Mg", "short_name":"Mg"},
"305":{"unit":"mg","long_name":"Phosphorus, P", "short_name":"Phos"},
"306":{"unit":"mg","long_name":"Potassium, K", "short_name":"Pota"},
"307":{"unit":"mg","long_name":"Sodium, Na", "short_name":"Sodi"},
"309":{"unit":"mg","long_name":"Zinc, Zn", "short_name":"Zinc"},
"312":{"unit":"mg","long_name":"Copper, Cu", "short_name":"Cu"},
"315":{"unit":"mg","long_name":"Manganese, Mn", "short_name":"Mn"},
"317":{"unit":"µg","long_name":"Selenium, Se", "short_name":"Sel"},
"320":{"unit":"µg","long_name":"Vitamin A, RAE", "short_name":"VitA"},
"323":{"unit":"mg","long_name":"Vitamin E (alpha-tocopherol)", "short_name":"VitE"},
"328":{"unit":"µg","long_name":"Vitamin D (D2 + D3)", "short_name":"VitD"},
"401":{"unit":"mg","long_name":"Vitamin C, total ascorbic acid", "short_name":"VitC"},
"404":{"unit":"mg","long_name":"Thiamin", "short_name":"B1"},
"405":{"unit":"mg","long_name":"Riboflavin", "short_name":"B2"},
"406":{"unit":"mg","long_name":"Niacin", "short_name":"B3"},
"410":{"unit":"mg","long_name":"Pantothenic acid", "short_name":"B5"},
"415":{"unit":"mg","long_name":"Vitamin B-6", "short_name":"B6"},
"417":{"unit":"µg","long_name":"Folate, total", "short_name":"B9"},
"418":{"unit":"µg","long_name":"Vitamin B-12", "short_name":"B12"},
"421":{"unit":"mg","long_name":"Choline, total", "short_name":"Chna"},
"430":{"unit":"µg","long_name":"Vitamin K (phylloquinone)", "short_name":"VitK"},
"601":{"unit":"mg","long_name":"Cholesterol", "short_name":"Chol"},
"606":{"unit":"g","long_name":"Fatty acids, total saturated", "short_name":"SatF"},
"618":{"unit":"g","long_name":"18:2 undifferentiated", "short_name":"Ω 6"},
"619":{"unit":"g","long_name":"18:3 undifferentiated", "short_name": "Ω 3"},
}
